# Generated by Django 5.0 on 2023-12-22 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamper',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
