# Generated by Django 5.0 on 2023-12-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamper', '0002_hamper_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamper',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
