# Generated by Django 5.0 on 2023-12-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamper', '0003_alter_hamper_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamper',
            name='soldtillnow',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
