# Generated by Django 5.0 on 2024-01-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamper', '0004_hamper_soldtillnow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamper',
            name='soldtillnow',
            field=models.IntegerField(),
        ),
    ]
